[package]
name = "math"
version = "0.1.0"
authors = ["fuookami <fuookami@163.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meta_programming = { git="https://github.com/fuookami/rust-meta-programming.git" }
rust_decimal = "1.9.0"
rust_decimal_macros = "1.9.0"
